### ISSUE TITLE
сделать валидацию входных данных

### ISSUE THREAD

**Issue by SerjAntiquity** [SerjAntiquity/roll.bot#1]
Аргументы roll должны быть int > 0

**Comment by treble-snake** [comment]
Ограничить кол-во кубов 10-20 штуками.
Ограничить грани кубов 30-гранником.

**Comment by SerjAntiquity** [comment]
@treble-snake 20 iштук?
Ответ представляешь? 6+5+4+5+6+8+4+2+3+1+5+4+6+1+5+1+3+5+3+4
я думаю 10 более чем достаточно.

**Comment by treble-snake** [comment]
Да, 10 вполне.
